#cloud-config
runcmd:
  - wget https://gist.githubusercontent.com/azatrg/772a709cc72731bf436e2585d78a0207/raw/2432fb763f8e8e51276e83f2ff885d360414ea3a/deploy_ruby_mongo_app.sh
  - bash deploy_ruby_mongo_app.sh
users:
  - name: yc-user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIHTTQb3yV+fCE4M1KFYPc3fvzgpB7J0TalgV3aigaS1/freGYiZtr6uwB/udzzfNL4DG5WL8C6tYgXpks5AiOI87pwAgnk5+eitrs9NM0k2fia+L6WxvaQlJizHEMIt+zrDLSoACTHheL4AGpXX18ou5fNL1MPlLeOxALIUaX9+QIAYaQtO8Y0ZjFAY/w8mme9oiCN1n4k44VtKpct0pi74IDkxj2DPfbzvGDmadiI+MRFQj7br+nsdcpBjaOK3pN6jDV1VeI2LxAQjH0sqHvFf1eSwBCPV2JWzV4mpcjkdqmkt9v2NkVnMziUvcn7xA2e/zI67NoogmPQBwyA2PSQSQFkjPlxYURVxKpJf3qgE6N0UiiU9W5vpYnVyFl+uwIpXAXacPTYwXxdZ2E+Wq9g0bNTv+sjGcaR5kMljbisibRcF3I5g8DlTAA4mAEUI0u7BHzZTwEx1fZzAHChOu7xlVnGrlOgM/GjaFc1kLpYOdN8C0jQmIbPepOMlDe+IC5/g53XNmEwUcKOfOts0tRfCukss4IsPLk19pdmz3x3PtJWtXK5+jwbYjmU7HRCaCtuIO1E6DFl5QBSJb1pgv4orIYcskLx8ma7tcpSi0k5bvKCMJccVS3SZ8947n1bPszsCtTWZC3l0AySzqvsDS7VDeEpW70WFKZR01O6kwubw== appuser
