---
- name: 'Install packages for app'
  hosts: default
  become: true

  tasks:
    - name: Install packages for app
      apt:
        update_cache: yes
        name:
        - ruby-full
        - ruby-bundler
        - build-essential
        - apt-transport-https
        - ca-certificates
        - git
        state: present
