- name: Configure application
  hosts: app
  become: true
  vars:
    db_host: 192.168.10.8
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for db connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu

    - name: Force systemd to reread configs
      systemd:
        daemon_reload: yes

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
  - name: reload puma
    become: true
    systemd: name=puma state=restarted
